CREATE TABLE `erp_product_specifics`(
    id int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `create_by` int(11) unsigned DEFAULT NULL,
    `update_by` int(11) unsigned DEFAULT NULL,
    puid varchar(100) NULL COMMENT '父uid',
    shop_id varchar(100) NULL COMMENT '店铺id',
    marketplace_id varchar(100) NULL COMMENT '市场id',
    full_cid varchar(100) NULL COMMENT 'FullCID',
    parent_id bigint(11) NULL COMMENT '父ID',
    dxm_state varchar(100) NULL COMMENT '产品状态',
    dxm_publish_state varchar(100) NULL COMMENT '产品发布状态',
    err_msg varchar(100) NULL COMMENT '错误信息',
    asin varchar(100) NULL COMMENT 'ASIN',
    listing_id varchar(100) NULL COMMENT 'Listing ID',
    parent_asin varchar(100) NULL COMMENT '父ASIN',
    child_asins varchar(100) NULL COMMENT '子ASIN',
    is_variation bigint(11) NULL COMMENT '是否变化',
    sku varchar(100) NULL COMMENT 'SKU',
    standard_product_type varchar(100) NULL COMMENT '标准产品类型',
    standard_product_id varchar(100) NULL COMMENT '标准产品ID',
    title varchar(100) NULL COMMENT '产品标题',
    brand varchar(100) NULL COMMENT '品牌',
    manufacturer varchar(100) NULL COMMENT '制造商',
    description varchar(100) NULL COMMENT '描述',
    bullet_point varchar(100) NULL COMMENT '重点',
    condition_type varchar(100) NULL COMMENT '条件类型',
    condition_value varchar(100) NULL COMMENT '条件值',
    standard_price Double NULL COMMENT '标准价格',
    listing_pricing Double NULL COMMENT '价格',
    switch_fulfillment_to varchar(100) NULL COMMENT '配送转换',
    fulfillment_channel varchar(100) NULL COMMENT '配送渠道',
    part_number varchar(100) NULL COMMENT '产品型号',
    main_image varchar(100) NULL COMMENT '主图',
    sale_start_date varchar(100) NULL COMMENT '开始售出日期',
    sale_end_date varchar(100) NULL COMMENT '销售结束日期',
    sale_sale_price varchar(100) NULL COMMENT '售价',
    quantity bigint(11) NULL COMMENT '数量',
    open_date varchar(100) NULL COMMENT '开放时间',
    item_dimensions varchar(100) NULL COMMENT '产品体积',
    package_dimensions varchar(100) NULL COMMENT '包裹体积',
    standard_price_currency varchar(100) NULL COMMENT '标准价格币种',
    specifics varchar(100) NULL COMMENT '详情',
    variation_child_str varchar(100) NULL COMMENT '变体？',
    online_status varchar(100) NULL COMMENT '在线状态',
    sale_num bigint(11) NULL COMMENT '销量',
    fnsku varchar(100) NULL COMMENT 'FNSKU',
    warehousing bigint(11) NULL COMMENT '库存',
    unsellable bigint(11) NULL COMMENT '不可售数量',
    reserved_qty bigint(11) NULL COMMENT '预留数量',
    purchase_cost bigint(11) NULL COMMENT '购买成本',
    head_trip_cost bigint(11) NULL COMMENT '头程费用',
    ship_cost varchar(100) NULL COMMENT '运费',
    price_feed_status varchar(100) NULL COMMENT '价格推送状态',
    inventory_feed_status varchar(100) NULL COMMENT '库存推送状态',
    update_standard_price varchar(100) NULL COMMENT '更新标准价格',
    update_quantity varchar(100) NULL COMMENT '更新数量',
    rating varchar(100) NULL COMMENT 'Rating',
    rating_count varchar(100) NULL COMMENT 'Rating数',
    `rank` varchar(100) NULL COMMENT '排名',
    bsr_rank varchar(100) NULL COMMENT 'BestSeller排名',
    commodity_id varchar(100) NULL COMMENT '商品id',
    dev_id varchar(100) NULL COMMENT '开发者id',
    create_id varchar(100) NULL COMMENT '创建id',
    update_id varchar(100) NULL COMMENT '更新id',
    lprice_update_time varchar(100) NULL COMMENT 'l价格更新时间',
    lprice_status varchar(100) NULL COMMENT 'l价格状态',
    child_list varchar(100) NULL COMMENT '子listing',
    sale_prices Double NULL COMMENT '销售额',
    ad_costs Double NULL COMMENT '广告费',
    currency varchar(100) NULL COMMENT '币种',
    cost_currency varchar(100) NULL COMMENT '广告费币种',
    commodity_sku varchar(100) NULL COMMENT '商品SKU',
    commodity_name varchar(100) NULL COMMENT '商品名称',
    shop_name varchar(100) NULL COMMENT '店铺名称',
    site_name varchar(100) NULL COMMENT '站点名称',
    domain varchar(100) NULL COMMENT '区域域名',
    child_num varchar(100) NULL COMMENT '子体数',
    dev_ids varchar(100) NULL COMMENT '业务员id',
    dev_name varchar(100) NULL COMMENT '业务员名称',
    variation_str_map varchar(100) NULL COMMENT '变化映射',
    listing_price Double NULL COMMENT 'Buy Box价格',
    shipping_price bigint(11) NULL COMMENT '运费',
    buy_box_winner varchar(100) NULL COMMENT 'Buy Box资格',
    buy_box_currency varchar(100) NULL COMMENT 'Buy Box币种',
    total_fee Double NULL COMMENT '总费用',
    referral_fee Double NULL COMMENT '销售佣金',
    variable_closing_fee bigint(11) NULL COMMENT '交易手续费',
    per_item_fee bigint(11) NULL COMMENT '计件费用',
    fba_fees Double NULL COMMENT 'FBA费用',
    fee_currency varchar(100) NULL COMMENT '费用币种',
    vartation_str varchar(100) NULL COMMENT '变化字符',
    bsr_rank_str varchar(100) NULL COMMENT 'BestSeller排名字符',
    PRIMARY KEY (`id`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='在线产品';

CREATE TABLE `erp_product_bsr`(
    id int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `create_by` int(11) unsigned DEFAULT NULL,
    `update_by` int(11) unsigned DEFAULT NULL,
    `rank` bigint(11) NULL COMMENT '排名',
    category_id varchar(100) NULL COMMENT '类目ID',
    category_name varchar(100) NULL COMMENT '类目名称',
    PRIMARY KEY (`id`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='产品类目排名';


CREATE TABLE `erp_product_inventory`(
    id int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `create_by` int(11) unsigned DEFAULT NULL,
    `update_by` int(11) unsigned DEFAULT NULL,
    puid bigint(11) NULL COMMENT '父uid',
    shop_id bigint(11) NULL COMMENT '店铺id',
    marketplace_id varchar(100) NULL COMMENT '市场id',
    full_cid varchar(100) NULL COMMENT 'Full CID',
    main_image varchar(100) NULL COMMENT '主图',
    asin varchar(100) NULL COMMENT 'ASIN',
    sku varchar(100) NULL COMMENT 'SKU',
    fn_sku varchar(100) NULL COMMENT 'FNSKU',
    `condition` varchar(100) NULL COMMENT '条件',
    commodity_id bigint(11) NULL COMMENT '商品ID',
    commodity_name varchar(100) NULL COMMENT '商品名称',
    commodity_sku varchar(100) NULL COMMENT '商品SKU',
    avg_inventory_cost bigint(11) NULL COMMENT '平均库存费用',
    avg_transport_cost bigint(11) NULL COMMENT '平均运输费用',
    inventory_costs Double NULL COMMENT '库存费用',
    purchase_costs bigint(11) NULL COMMENT '购买成本',
    currency varchar(100) NULL COMMENT '币种',
    available bigint(11) NULL COMMENT '可售数量',
    reserved_transfer bigint(11) NULL COMMENT '待调仓',
    reserved_processing bigint(11) NULL COMMENT '调仓中',
    reserved_customerorders bigint(11) NULL COMMENT '待发货',
    inbound_working bigint(11) NULL COMMENT '计划入库',
    inbound_shipped bigint(11) NULL COMMENT '在途',
    inbound_receiving bigint(11) NULL COMMENT '入库中',
    unfulfillable bigint(11) NULL COMMENT '不可售',
    inv_age0to90_days bigint(11) NULL COMMENT '0到90天库存',
    inv_age91_to180_days bigint(11) NULL COMMENT '91到180天库存',
    inv_age181_to270_days bigint(11) NULL COMMENT '181到270天库存',
    inv_age271_to365_days bigint(11) NULL COMMENT '271到365天库存',
    inv_age365_plus_days bigint(11) NULL COMMENT '365+天库存',
    total_inventory bigint(11) NULL COMMENT '总计库存',
    full_cid_name varchar(100) NULL COMMENT 'Full CID名称',
    PRIMARY KEY (`id`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='产品库存';
