CREATE TABLE `erp_finance_transaction`(
    id int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `create_by` int(11) unsigned DEFAULT NULL,
    `update_by` int(11) unsigned DEFAULT NULL,
    payment_time varchar(100) NULL COMMENT '结算日期',
    earliest_ship_date varchar(100) NULL COMMENT '发货日期',
    main_image varchar(100) NULL COMMENT '图片',
    asin varchar(100) NULL COMMENT 'ASIN',
    commodity_name varchar(100) NULL COMMENT '品名',
    commodity_sku varchar(100) NULL COMMENT '商品SKU',
    purchase_cost varchar(100) NULL COMMENT '采购成本',
    head_trip_cost varchar(100) NULL COMMENT '头程费用',
    gross_profit varchar(100) NULL COMMENT '毛利润',
    currency varchar(100) NULL COMMENT '币种',
    domain varchar(100) NULL COMMENT 'domain',
    shop_id bigint(11) NULL COMMENT '店铺id',
    shop_name varchar(100) NULL COMMENT '店铺名字',
    market_place_id varchar(100) NULL COMMENT '市场ID',
    settlement_id varchar(100) NULL COMMENT '结算ID',
    type varchar(100) NULL COMMENT '交易类型',
    description varchar(100) NULL COMMENT '描述',
    order_id varchar(100) NULL COMMENT '订单号',
    account_type varchar(100) NULL COMMENT '类型',
    sku varchar(100) NULL COMMENT 'MSKU',
    marketplace varchar(100) NULL COMMENT '销售市场',
    fulfillment varchar(100) NULL COMMENT '发货方式',
    quantity bigint(11) NULL COMMENT '数量',
    product_sales varchar(100) NULL COMMENT '销售价格',
    shipping_credits varchar(100) NULL COMMENT '运费',
    gift_wrap_credits varchar(100) NULL COMMENT '礼品包装费',
    promotional_rebates varchar(100) NULL COMMENT '促销返点',
    product_sales_tax varchar(100) NULL COMMENT '销售税',
    marketplace_withheld_tax varchar(100) NULL COMMENT '市场税',
    selling_fees varchar(100) NULL COMMENT '平台佣金',
    fba_fees varchar(100) NULL COMMENT 'FBA Fees',
    other_transaction_fees varchar(100) NULL COMMENT '其他交易费',
    other varchar(100) NULL COMMENT '其他费',
    total varchar(100) NULL COMMENT '亚马逊结算小计',
    integral varchar(100) NULL COMMENT '积分',
    order_other_fee varchar(100) NULL COMMENT '订单其他佣金',
    evaluation_fee varchar(100) NULL COMMENT '评估费用',
    fbm_ship_cost varchar(100) NULL COMMENT 'FBM 运费',
    PRIMARY KEY (`id`) USING BTREE
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='结算明细';
